### ISSUE TITLE
CRASHES WHILE USING IT ON  A SERVER WITH THE NEW VERSION OF TODAY 

### ISSUE THREAD

**Issue by Lokemol** [Flytre/BiomeLocator#3]
I needed to downgrade the version to the one from jul 11 the biome_locator-1.17.1-1.1.3.jar because when using the 1.3.0 on  a server it gives this error
---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/13/21, 11:43 AM
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.longs.LongArrayList.getLong(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:755)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:751)
	at net.minecraft.class_3204.method_14045(class_3204.java:547)
	at net.minecraft.class_3215.method_12127(class_3215.java:321)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.md2e9bc2$lambda$tickWorlds$0$2(MinecraftServer.java:2320)
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34)
	at net.minecraft.server.MinecraftServer.md2e9bc2$lambda$tickWorlds$1$1(MinecraftServer.java:2318)
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49)
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:755)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:751)
	at net.minecraft.class_3204.method_14045(class_3204.java:547)
	at net.minecraft.class_3215.method_12127(class_3215.java:321)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 841
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-208,70,96), Section: (at 0,6,0 in -13,4,6; chunk contains blocks -208,0,96 to -193,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 12636361 game time, 15380188 day time
	Level name: MUNDO SEXO
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 76439 (now: false), thunder time: 66156 (now: false)
	Known server brands: fabric, vanilla
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:11)
	at net.minecraft.server.MinecraftServer.handler$zkj000$tickWorlds(MinecraftServer.java:2330)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:880)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.handler$beo000$modifiedRunLoop(MinecraftServer.java:4890)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 856565392 bytes (816 MiB) / 2147483648 bytes (2048 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37564.63
	Virtual memory used (MB): 15055.96
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 2.25
	JVM Flags: 2 total; -Xms1024M -Xmx10240M
	Fabric Mods: 
		appleskin: AppleSkin mc1.17-2.1.2
		architectury: Architectury 2.2.21
		betterthanmending: BetterThanMending 1.3.0
		biome_locator: Biome Locator 1.1.3
		blue_endless_jankson: jankson 1.2.1
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_github_wearblackallday_javautils: JavaUtils 1b369d41cd
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		deepslatecutting: Deepslate Cutting 1.2.0
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		dimthread: DimensionalThreading 1.2.5
		easy_painter: Easy Painter 1.0.2
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fallingtree: FallingTree 2.12.0
		ferritecore: FerriteCore 3.0.1
		flan: Flan 1.17.1-1.6.1
		flytre_lib: FlytreLib 0.2.21
		grindenchantments: Grind Enchantments 1.2.1+1.17
		harvest: Harvest 1.2.12
		hydrogen: Hydrogen 0.3
		inmis: Inmis 2.3.1-1.17
		inventorysorter: Inventory Sorter 1.7.9-1.17
		java: Java HotSpot(TM) 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.3
		minecraft: Minecraft 1.17.1
		noexpensive: NoExpensive 1.17-Fabric-1.2.0
		omega-config: OmegaConfig 1.0.8
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		perfectaccuracy: Perfect Accuracy 1.1
		recipecache: recipecache 0.2.0-1.17.1
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		server_translations_api: Server Translations API 1.4.4+1.17
		sgui: SGui 1.0.0-pre0-1.17-pre1
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		worldspecificviewdistance: World Specific View Distance 0.1.0-1.17
	Player Count: 1 / 7; [class_3222['Lokemol'/236, l='ServerLevel[MUNDO SEXO]', x=104.24, y=57.00, z=-11.64]]
	Data Packs: vanilla, file/Back to blocks.zip, file/Charcoal to dye.zip, file/More Bricks.zip, file/Straight to shapeless.zip, file/armored elytra v1.0.3.zip, file/classic fishing loot v1.1.0.zip, file/coal to black dye.zip, file/craftable notch apples.zip, file/double slabs.zip, file/dragon drops v1.3.0.zip, file/graves v2.8.4.zip, file/larger phantoms v1.2.1.zip, file/more bark.zip, file/more stairs.zip, file/more trapdoors.zip, file/nether portal coords v1.1.0.zip, file/powder to glass.zip, file/universal dyeing.zip, file/unpackable ice.zip, file/unpackable nether wart.zip, file/villager death messages v1.2.1.zip, file/villager workstation highlights v1.1.0.zip, file/snowy.zip, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Monster-Zer0** [comment]
*Bump*

https://paste.alloffabric.com/enayadukij.yaml

https://github.com/TeamAOF/All-of-Fabric-4/issues/108
